name: anomalyDetection
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cycler=0.10.0
  - django=2.2.5
  - et_xmlfile=1.0.1
  - freetype=2.10.0
  - icc_rt=2019.0.0
  - icu=64.2
  - intel-openmp=2019.4
  - jdcal=1.4.1
  - joblib=0.13.2
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - numpy=1.17.2
  - openpyxl=3.0.0
  - openssl=1.1.1d
  - pandas=0.25.1
  - pip=19.3.1
  - py4j=0.10.7
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyspark=2.4.4
  - python=3.6.7
  - python-dateutil=2.8.0
  - pytz=2019.2
  - qt=5.9.7
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - sqlparse=0.3.0
  - tornado=6.0.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.33.6
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - fanstatic==1.1
    - js-d3==3.5.5
    - shutilwhich==1.1.0
    - webob==1.8.5
    - xlrd==1.2.0

